In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder, OneHotEncoder
import pickle

In [3]:
data = pd.read_csv("./Churn_Modelling.csv")

data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# Preprocess the data
data = data.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [5]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])

In [9]:
# One Hot Encode "Geography"
onehot_encoder_geo = OneHotEncoder(handle_unknown="ignore")
geo_encoded= onehot_encoder_geo.fit_transform(data[["Geography"]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop("Geography",axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
# Split the data into features  and target
X = data.drop("EstimatedSalary",axis=1)
y = data["EstimatedSalary"]

In [12]:
## Split the data in training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
## Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
## Save the encoders and scaler
with open("label_encoder_gender.pkl","wb") as file:
    pickle.dump(label_encoder_gender,file)

with open("onehot_encoder_geo.pkl","wb") as file:
    pickle.dump(onehot_encoder_geo,file)

with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

## ANN Regression Problem Statem

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [16]:
## Build Our ANN Model
model = Sequential([
    Dense(64,activation="relu",input_shape=(X_train.shape[1],)), ## HL1 connected with input layer
    Dense(32,activation="relu"), ##L2
    Dense(1) ## output layer
])

## Compile the model
model.compile(optimizer="adam",loss="mean_absolute_error",metrics=["mae"])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [20]:
early_stopping_callback = EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [21]:
### Train the model
history = model.fit(
    X_train,y_train,validation_data =(X_test,y_test),epochs=100,callbacks=[early_stopping_callback,tensorflow_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 100378.6797 - mae: 100378.6797 - val_loss: 98525.1016 - val_mae: 98525.1016
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 99660.8594 - mae: 99660.8594 - val_loss: 97071.2422 - val_mae: 97071.2422
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 97118.8047 - mae: 97118.8047 - val_loss: 93326.8438 - val_mae: 93326.8438
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 92083.3359 - mae: 92083.3359 - val_loss: 87043.3281 - val_mae: 87043.3281
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 84685.6016 - mae: 84685.6016 - val_loss: 78830.6406 - val_mae: 78830.6406
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 75833.3125 - mae: 75833.3125 - val_loss: 70075.4766 - val_mae: 70075.4766
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 67039.6719 - mae: 67039.6719 - val_loss: 62208.5156 - val_mae: 62208.5156
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 59725.4570 - mae: 59725.4570 - val_loss: 56365.4688 - val_mae: 56365.4688
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 54794.0508 - mae: 54794.0508 - val_loss: 52928.6719 - val_mae: 52928.6719
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 51974.9297 - mae: 51974.9297 - val_loss: 51406.4023 - val_mae: 51406.4023
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 50787.2305 - mae: 50787.2305 - val_loss: 50941.6367 - val_mae: 50941.6367
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50347.1250 - mae: 50347.1250 - val_loss: 50803.9414 - val_mae: 50803.9414
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50193.6367 - mae: 50193.6367 - val_loss: 50750.8320 - val_mae: 50750.8320
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 50112.4414 - mae: 50112.4414 - val_loss: 50724.6133 - val_mae: 50724.6133
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 50055.3203 - mae: 50055.3203 - val_loss: 50704.9258 - val_mae: 50704.9258
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 50011.8945 - mae: 50011.8945 - val_loss: 50687.6562 - val_mae: 50687.6562
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 49973.6406 - mae: 49973.6406 - val_loss: 50661.4141 - val_mae: 50661.4141
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 49936.5664 - mae: 49936.5664 - val_loss: 50642.1055 - val_mae: 50642.1055
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 49903.0977 - mae: 49903.0977 - val_loss: 50623.5078 - val_mae: 50623.5078
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 49874.8047 - mae: 49874.8047 - val_loss: 50602.1641 - val_mae: 50602.1641
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 49848.9023 - mae: 49848.9023 - val_loss: 50582.1836 - val_mae: 50582.1836
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49825.0352 - mae: 49825.0352 - val_loss: 50569.6094 - val_mae: 50569.6094
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 49806.4805 - mae: 49806.4805 - val_loss: 50552.2578 - val_mae: 50552.2578
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49780.6562 - mae: 49780.6562 - val_loss: 50536.8164 - val_mae: 50536.8164
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49764.0664 - mae: 49764.0664 - val_loss: 50533.6445 - val_mae: 50533.6445
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49745.0039 - mae: 49745.0039 - val_loss: 50511.2734 - val_mae: 50511.2734
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49723.8008 - mae: 49723.8008 - val_loss: 50498.4609 - val_mae: 50498.4609
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 49707.8203 - mae: 49707.8203 - val_loss: 50487.8008 - val_mae: 50487.8008
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49691.6211 - mae: 49691.6211 - val_loss: 50479.2188 - val_mae: 50479.2188
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49674.2031 - mae: 49674.2031 - val_loss: 50480.3750 - val_mae: 50480.3750
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 49655.8984 - mae: 49655.8984 - val_loss: 50454.3281 - val_mae: 50454.3281
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 49647.0742 - mae: 49647.0742 - val_loss: 50458.8633 - val_mae: 50458.8633
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49630.6719 - mae: 49630.6719 - val_loss: 50444.6602 - val_mae: 50444.6602
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49617.4062 - mae: 49617.4062 - val_loss: 50444.1406 - val_mae: 50444.1406
Epoch 35/100
250/250 [==============================] - 0s 1ms/step - loss: 49603.4258 - mae: 49603.4258 - val_loss: 50428.3633 - val_mae: 50428.3633
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: 49592.9961 - mae: 49592.9961 - val_loss: 50426.2344 - val_mae: 50426.2344
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: 49582.0938 - mae: 49582.0938 - val_loss: 50418.4805 - val_mae: 50418.4805
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49569.3008 - mae: 49569.3008 - val_loss: 50416.8750 - val_mae: 50416.8750
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 49559.1406 - mae: 49559.1406 - val_loss: 50402.7344 - val_mae: 50402.7344
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49548.4805 - mae: 49548.4805 - val_loss: 50400.9062 - val_mae: 50400.9062
Epoch 41/100
250/250 [==============================] - 0s 1ms/step - loss: 49542.0859 - mae: 49542.0859 - val_loss: 50396.4570 - val_mae: 50396.4570
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 49533.1055 - mae: 49533.1055 - val_loss: 50392.3984 - val_mae: 50392.3984
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49529.0703 - mae: 49529.0703 - val_loss: 50394.0469 - val_mae: 50394.0469
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49515.8086 - mae: 49515.8086 - val_loss: 50381.6562 - val_mae: 50381.6562
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49510.2031 - mae: 49510.2031 - val_loss: 50368.7539 - val_mae: 50368.7539
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 49499.3555 - mae: 49499.3555 - val_loss: 50374.9336 - val_mae: 50374.9336
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49493.3867 - mae: 49493.3867 - val_loss: 50368.9023 - val_mae: 50368.9023
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49487.2188 - mae: 49487.2188 - val_loss: 50372.0156 - val_mae: 50372.0156
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49477.5039 - mae: 49477.5039 - val_loss: 50375.3281 - val_mae: 50375.3281
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: 49470.7461 - mae: 49470.7461 - val_loss: 50371.2656 - val_mae: 50371.2656
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 49465.8320 - mae: 49465.8320 - val_loss: 50369.0352 - val_mae: 50369.0352
Epoch 52/100
250/250 [==============================] - 0s 1ms/step - loss: 49460.8945 - mae: 49460.8945 - val_loss: 50367.7227 - val_mae: 50367.7227
Epoch 53/100
250/250 [==============================] - 1s 2ms/step - loss: 49453.8711 - mae: 49453.8711 - val_loss: 50378.0000 - val_mae: 50378.0000
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 49447.0352 - mae: 49447.0352 - val_loss: 50367.6094 - val_mae: 50367.6094
Epoch 55/100
250/250 [==============================] - 0s 1ms/step - loss: 49442.3516 - mae: 49442.3516 - val_loss: 50360.5273 - val_mae: 50360.5273
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 49432.9844 - mae: 49432.9844 - val_loss: 50361.5508 - val_mae: 50361.5508
Epoch 57/100
250/250 [==============================] - 0s 1ms/step - loss: 49425.9844 - mae: 49425.9844 - val_loss: 50361.9766 - val_mae: 50361.9766
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: 49423.1758 - mae: 49423.1758 - val_loss: 50367.2305 - val_mae: 50367.2305
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 49415.6055 - mae: 49415.6055 - val_loss: 50357.2344 - val_mae: 50357.2344
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: 49411.5117 - mae: 49411.5117 - val_loss: 50366.9922 - val_mae: 50366.9922
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49406.6172 - mae: 49406.6172 - val_loss: 50363.1055 - val_mae: 50363.1055
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 49404.8320 - mae: 49404.8320 - val_loss: 50368.1133 - val_mae: 50368.1133
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 49398.1562 - mae: 49398.1562 - val_loss: 50365.6484 - val_mae: 50365.6484
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 49391.7305 - mae: 49391.7305 - val_loss: 50356.3594 - val_mae: 50356.3594
Epoch 65/100
250/250 [==============================] - 1s 2ms/step - loss: 49388.4883 - mae: 49388.4883 - val_loss: 50359.1641 - val_mae: 50359.1641
Epoch 66/100
250/250 [==============================] - 0s 1ms/step - loss: 49378.7539 - mae: 49378.7539 - val_loss: 50372.1797 - val_mae: 50372.1797
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 49382.3984 - mae: 49382.3984 - val_loss: 50364.6914 - val_mae: 50364.6914
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 49372.8789 - mae: 49372.8789 - val_loss: 50363.3086 - val_mae: 50363.3086
Epoch 69/100
250/250 [==============================] - 1s 2ms/step - loss: 49367.9414 - mae: 49367.9414 - val_loss: 50362.8516 - val_mae: 50362.8516
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 49366.2891 - mae: 49366.2891 - val_loss: 50365.3242 - val_mae: 50365.3242
Epoch 71/100
250/250 [==============================] - 0s 2ms/step - loss: 49360.9414 - mae: 49360.9414 - val_loss: 50361.7773 - val_mae: 50361.7773
Epoch 72/100
250/250 [==============================] - 0s 2ms/step - loss: 49357.5508 - mae: 49357.5508 - val_loss: 50359.3125 - val_mae: 50359.3125
Epoch 73/100
250/250 [==============================] - 0s 1ms/step - loss: 49352.6875 - mae: 49352.6875 - val_loss: 50357.3594 - val_mae: 50357.3594
Epoch 74/100
250/250 [==============================] - 1s 2ms/step - loss: 49350.6406 - mae: 49350.6406 - val_loss: 50354.5000 - val_mae: 50354.5000
Epoch 75/100
250/250 [==============================] - 0s 2ms/step - loss: 49343.2695 - mae: 49343.2695 - val_loss: 50351.1719 - val_mae: 50351.1719
Epoch 76/100
250/250 [==============================] - 0s 2ms/step - loss: 49341.7539 - mae: 49341.7539 - val_loss: 50367.8984 - val_mae: 50367.8984
Epoch 77/100
250/250 [==============================] - 0s 2ms/step - loss: 49337.0234 - mae: 49337.0234 - val_loss: 50371.7109 - val_mae: 50371.7109
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 49335.7070 - mae: 49335.7070 - val_loss: 50365.4766 - val_mae: 50365.4766
Epoch 79/100
250/250 [==============================] - 0s 2ms/step - loss: 49330.2461 - mae: 49330.2461 - val_loss: 50365.8711 - val_mae: 50365.8711
Epoch 80/100
250/250 [==============================] - 1s 4ms/step - loss: 49327.1719 - mae: 49327.1719 - val_loss: 50363.0000 - val_mae: 50363.0000
Epoch 81/100
250/250 [==============================] - 1s 5ms/step - loss: 49325.5547 - mae: 49325.5547 - val_loss: 50369.0586 - val_mae: 50369.0586
Epoch 82/100
250/250 [==============================] - 1s 5ms/step - loss: 49321.1758 - mae: 49321.1758 - val_loss: 50377.5938 - val_mae: 50377.5938
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 49319.2344 - mae: 49319.2344 - val_loss: 50376.7109 - val_mae: 50376.7109
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 49317.1562 - mae: 49317.1562 - val_loss: 50365.9141 - val_mae: 50365.9141
Epoch 85/100
250/250 [==============================] - 1s 4ms/step - loss: 49315.6172 - mae: 49315.6172 - val_loss: 50352.3984 - val_mae: 50352.3984

In [ ]:
## Evaluate the model

In [22]:
%load_ext tensorboard

In [25]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6008 (pid 127275), started 0:01:11 ago. (Use '!kill 127275' to kill it.)

In [27]:
## Evaluate model on the test data
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 811us/step - loss: 50351.1719 - mae: 50351.1719
Test MAE : 50351.171875

In [28]:
model.save("regression_model.h5")

/workspaces/ann-classification/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(